import { ArrowUpRight, Check, MapPin, MessageCircle, Menu, X } from "lucide-react";
import { useState } from "react";
import { site } from "./site";
function External({ href, children, className = "button" }: { href: string; children: React.ReactNode; className?: string }) { return <a className={className} href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={18} /></a>; }
export default function App() { const [open, setOpen] = useState(false); return <div className="site" style={{ "--accent": site.accent, "--ink": site.ink, "--paper": site.paper } as React.CSSProperties}>
  <a className="skip" href="#conteudo">Pular para o conteúdo</a><header><a className="brand" href="#inicio"><img className="brand-logo" src="/images/brand.jpg" alt="" width="48" height="48" />{site.name}<small>{site.category}</small></a><nav className={open ? "open" : ""}><a href="#sobre" onClick={() => setOpen(false)}>Sobre</a><a href="#servicos" onClick={() => setOpen(false)}>{site.servicesLabel}</a><a href="#contato" onClick={() => setOpen(false)}>Contato</a></nav><External href={site.contactUrl}>Falar agora</External><button className="menu" onClick={() => setOpen(!open)} aria-label="Abrir menu">{open ? <X /> : <Menu />}</button></header>
  <main id="conteudo"><section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">{site.eyebrow}</p><h1>{site.headlineBefore}<em>{site.headlineEm}</em>{site.headlineAfter}</h1><p className="lead">{site.description}</p><External href={site.contactUrl}>{site.cta}</External><p className="micro"><Check size={16} /> {site.microcopy}</p></div><div className="hero-art hero-video"><video autoPlay muted loop playsInline controls preload="metadata" poster={site.image} aria-label="Apresentação dos serviços da Stop Car"><source src="/media/hero-vsl.mp4" type="video/mp4" />Seu navegador não consegue reproduzir este vídeo.</video><div className="hero-stamp">{site.stamp}</div></div></section><div className="ticker" aria-hidden="true">{[...site.highlights, ...site.highlights, ...site.highlights].join(" ✦ ")}</div>
  <section className="section split" id="sobre"><div><p className="eyebrow">{site.aboutEyebrow}</p><h2>{site.aboutTitle}<em>{site.aboutEm}</em></h2></div><div><p>{site.about}</p><External href={site.contactUrl} className="text-link">{site.secondaryCta}</External></div></section><section className="section" id="servicos"><p className="eyebrow">{site.servicesLabel}</p><h2>{site.servicesTitle}<em>{site.servicesEm}</em></h2><div className="cards">{site.services.map((service, index) => <External href={site.contactUrl} className="card" key={service}><span>0{index + 1}</span><h3>{service}</h3><p>{site.serviceDescriptions[index]}</p><b>Saiba mais <ArrowUpRight size={16} /></b></External>)}</div>{site.disclaimer && <p className="disclaimer">{site.disclaimer}</p>}</section>
  <section className="location section" id="contato"><div><p className="eyebrow">ONDE ENCONTRAR</p><h2>{site.locationTitle}<em>{site.locationEm}</em></h2><p>{site.locationText}</p><address><MapPin size={19} /><span><strong>{site.address}</strong><small>{site.city}</small></span></address><div className="actions"><External href={site.contactUrl}>{site.cta}</External>{site.mapUrl && <External href={site.mapUrl} className="text-link">Como chegar</External>}</div></div><div className="contact-panel"><img src="/images/photo-2.jpg" alt="Orientações da Stop Car sobre balanceamento" loading="lazy" decoding="async" /><p>{site.contactPrompt}</p><External href={site.contactUrl} className="button button-light">{site.secondaryCta}</External></div></section></main>
  <footer><a className="brand" href="#inicio"><img className="brand-logo" src="/images/brand.jpg" alt="" width="48" height="48" />{site.name}<small>{site.category}</small></a><p>{site.footer}</p><External href={site.instagramUrl} className="text-link">Instagram</External></footer><External href={site.contactUrl} className="button float"><MessageCircle /><span className="sr-only">Entrar em contato com {site.name}</span></External></div>; }
