import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowUpRight, Camera, Check, Dumbbell, Menu, MessageCircle, ShieldCheck, Sparkles, Target, X, Zap } from "lucide-react";

const instagramUrl = "https://www.instagram.com/duh.personal/";
const whatsappUrl = instagramUrl;
const errors = [
  ["01", "Treinar sem um plano que conversa com o seu objetivo e com a sua rotina."],
  ["02", "Repetir treinos genéricos e esperar que o corpo responda sozinho."],
  ["03", "Mudar de estratégia toda semana sem medir, ajustar ou criar consistência."],
  ["04", "Achar que resultado depende de motivação constante, e não de direção."],
];
const pillars = [
  { icon: Dumbbell, title: "Treino personalizado", text: "Estratégia construída para o seu nível, objetivo, rotina e experiência." },
  { icon: Target, title: "Avaliação real", text: "Ponto de partida claro, presencialmente ou por fotos, para orientar cada ajuste." },
  { icon: Zap, title: "Ajustes contínuos", text: "O plano evolui com você, com acompanhamento próximo e suporte pelo WhatsApp." },
  { icon: ShieldCheck, title: "Resultado sustentável", text: "Mais clareza para treinar, alimentar-se e seguir em frente com consistência." },
];

function Brand() { return <a className="brand" href="#inicio" aria-label="DU Personal — início"><span className="brand-mark"><img src="/favicon.png" alt="" /></span><span className="brand-copy">DU<br /><strong>PERSONAL</strong></span></a>; }
function ActionLink({ href, children, tone = "lime" }: { href: string; children: React.ReactNode; tone?: "lime" | "ghost" | "white" }) { return <a className={`button button-${tone}`} href={href} target="_blank" rel="noopener noreferrer"><span>{children}</span><ArrowUpRight size={18} /></a>; }

function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [privacyOpen, setPrivacyOpen] = useState(false); const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("visible")), { threshold: .12 }); document.querySelectorAll(".reveal").forEach((node) => observer.observe(node)); return () => observer.disconnect(); }, []);
  useEffect(() => { if (privacyOpen) dialog.current?.showModal(); else dialog.current?.close(); }, [privacyOpen]);
  return <div className="site"><a href="#conteudo" className="skip-link">Pular para o conteúdo</a>
    <header className="header"><Brand /><nav className={menuOpen ? "nav is-open" : "nav"} aria-label="Navegação principal"><a href="#metodo" onClick={() => setMenuOpen(false)}>O método</a><a href="#programas" onClick={() => setMenuOpen(false)}>Consultoria</a><a href="#duh" onClick={() => setMenuOpen(false)}>DU Personal</a><a href="#duvidas" onClick={() => setMenuOpen(false)}>Dúvidas</a></nav><a className="header-cta" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Quero evoluir <ArrowUpRight size={16} /></a><button className="menu-button" type="button" aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></header>
    <main id="conteudo">
      <section className="hero" id="inicio"><div className="hero-grid"><div className="hero-copy reveal"><div className="overline"><span /> DU PERSONAL · ONLINE & PRESENCIAL</div><h1>Treino com propósito. <em>Resultado que transforma.</em></h1><p className="hero-lead">Você não precisa de mais um treino solto. Precisa de um plano que entende seu corpo, sua rotina e o próximo passo.</p><div className="hero-actions"><ActionLink href={whatsappUrl}>Falar com o DU Personal</ActionLink><a className="text-link" href="#programas">Conhecer a consultoria <ArrowDown size={16} /></a></div><div className="trust-row"><div><strong>CREF 209470-G/SP</strong><span>profissional registrado</span></div><div><strong>Online + presencial</strong><span>formato que se adapta</span></div><div><strong>VAMO QUERER!?</strong><span>método com propósito</span></div></div></div><div className="hero-visual reveal"><div className="portrait-frame"><img src="/images/educador-fisico.jpg" alt="Eduardo Cassanta, DU Personal" fetchPriority="high" /><div className="portrait-label"><span>PERSONAL TRAINER</span><strong>DU PERSONAL</strong></div></div><div className="day-seal"><strong>DU</strong><span>PERSONAL</span></div><div className="live-chip"><span className="pulse" /> ACOMPANHAMENTO REAL</div><span className="outline-word" aria-hidden="true">QUERER</span></div></div><div className="hero-foot"><span>01</span><div /><p>Ensino com ciência. Treino com propósito.</p></div></section>
      <div className="marquee" aria-label="DU Personal"><div className="marquee-track" aria-hidden="true">{[0,1].map((item) => <span key={item}>DU PERSONAL <b>✦</b> TREINO <b>✦</b> PROPÓSITO <b>✦</b> RESULTADO <b>✦</b> VAMO QUERER!? <b>✦</b> </span>)}</div></div>
      <section className="diagnosis section" id="metodo"><div className="section-intro reveal"><span className="eyebrow">O PROBLEMA NÃO É FALTA DE VONTADE</span><h2>Esforço sem direção vira <em>frustração.</em></h2><p>Quando você recebe um plano genérico, fica difícil saber se está no caminho certo. A consultoria começa entendendo onde você está para construir o que vem depois.</p></div><div className="error-list reveal">{errors.map(([number, text]) => <article key={number}><span>{number}</span><p>{text}</p><X size={20} /></article>)}</div></section>
      <section className="method section-dark"><div className="method-head section reveal"><span className="eyebrow lime">A METODOLOGIA DU PERSONAL</span><h2>Um sistema para você <em>evoluir.</em></h2><p>Ciência, acompanhamento e ajustes. O treino deixa de ser uma tarefa isolada e passa a fazer sentido dentro da sua vida.</p></div><div className="pillars section reveal">{pillars.map(({icon: Icon,title,text}, index) => <article className="pillar" key={title}><div className="pillar-number">0{index+1}</div><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="programs section" id="programas"><div className="section-intro compact reveal"><span className="eyebrow">DOIS FORMATOS. UMA DIREÇÃO.</span><h2>O acompanhamento que combina com o seu <em>momento.</em></h2></div><div className="program-grid reveal"><article className="program-card challenge-card"><div className="program-top"><span>MAIS AUTONOMIA</span><strong>01</strong></div><h3>Consultoria<br />Online</h3><p className="program-description">Treino personalizado no aplicativo, com vídeos explicativos e uma estrutura clara para você executar onde estiver.</p><ul><li><Check /> Treino individualizado</li><li><Check /> Vídeos explicativos</li><li><Check /> Avaliação física</li><li><Check /> Ajustes constantes</li><li><Check /> Suporte contínuo no WhatsApp</li><li><Check /> Planos mensais, trimestrais e semestrais</li></ul><ActionLink href={whatsappUrl}>Quero conhecer a consultoria</ActionLink></article><article className="program-card consulting-card"><div className="program-top"><span>MAIOR PROXIMIDADE</span><strong>02</strong></div><h3>Consultoria<br />+ Dieta + Personal</h3><p className="program-description">Para quem quer unir treino, plano alimentar personalizado e acompanhamento presencial em uma experiência completa.</p><div className="consulting-message"><MessageCircle /><p><strong>Seu próximo passo começa em uma conversa.</strong> Conte seu objetivo, rotina e histórico. O DU Personal indica o formato mais adequado.</p></div><ActionLink href={whatsappUrl} tone="white">Falar com o DU Personal</ActionLink></article></div></section>
      <section className="authority" id="duh"><div className="authority-photo reveal"><img src="/images/consultoria.jpg" alt="Eduardo Cassanta apresentando a consultoria DU Personal" /><span className="image-caption">A CONSULTORIA EVOLUIU.</span></div><div className="authority-copy reveal"><span className="eyebrow lime">DU PERSONAL · CREF 209470-G/SP</span><h2>Mais que um profissional. Um guia para a sua <em>melhor versão.</em></h2><p>Eduardo Cassanta é Personal Trainer especialista em resultados, com atendimento online e presencial. O trabalho parte da ciência, mas acontece na prática: entendendo seu momento, ajustando o plano e mantendo você em movimento.</p><p>Porque treinar não é cumprir uma lista. É aprender a fazer escolhas que transformam o corpo e a relação com ele.</p><a className="instagram-link" href={instagramUrl} target="_blank" rel="noopener noreferrer"><Camera /> Acompanhar no Instagram <ArrowUpRight size={17} /></a></div></section>
      <section className="proof section"><div className="proof-copy reveal"><span className="eyebrow">RESULTADO É PROCESSO</span><h2>Quando existe método, a evolução fica <em>visível.</em></h2><p>O ponto de partida de cada aluno é único. Por isso a consultoria acompanha, mede e ajusta a estratégia em vez de prometer uma fórmula igual para todos.</p><div className="proof-notes"><span><Check /> Plano individual</span><span><Check /> Avaliação e ajustes</span><span><Check /> Suporte de verdade</span></div></div><figure className="proof-image reveal"><img src="/images/duh-profile.jpg" alt="DU Personal — ensino com ciência e treino com propósito" /><figcaption>Ensino com ciência. Treino com propósito. Resultados que transformam.</figcaption></figure></section>
      <section className="fit section-dark"><div className="section fit-grid"><div className="fit-copy reveal"><span className="eyebrow lime">É PARA VOCÊ?</span><h2>Você não precisa esperar o momento <em>perfeito.</em></h2><p>Precisa de uma direção compatível com a vida que existe hoje.</p></div><div className="fit-list reveal">{["Quer um treino alinhado ao seu objetivo", "Precisa de acompanhamento para manter a consistência", "Treina em casa, na academia ou alterna os dois", "Está disposto a participar ativamente do processo", "Busca resultado com estratégia e segurança"].map((item) => <div key={item}><Check /> <span>{item}</span></div>)}</div></div></section>
      <section className="offer section"><div className="offer-panel reveal"><div className="offer-badge"><Sparkles /><span>DU<br /><small>PERSONAL</small></span></div><div className="offer-copy"><span className="eyebrow">VAMO QUERER!?</span><h2>Seu próximo passo começa com <em>clareza.</em></h2><p>Converse com o DU Personal sobre seu objetivo, sua rotina e o formato de acompanhamento que faz sentido para você.</p></div><div className="offer-buy"><span>ATENDIMENTO ONLINE E PRESENCIAL</span><ActionLink href={whatsappUrl}>Quero começar</ActionLink><small><ShieldCheck /> Atendimento personalizado</small></div></div></section>
      <section className="faq section" id="duvidas"><div className="faq-heading reveal"><span className="eyebrow">ANTES DE COMEÇAR</span><h2>Dúvidas<br /><em>frequentes.</em></h2><p>Se ainda quiser conversar, fale diretamente com o DU Personal pelo Instagram.</p><ActionLink href={instagramUrl} tone="ghost">Tirar outra dúvida</ActionLink></div><div className="faq-list reveal">{[["A consultoria é online ou presencial?","Os dois formatos estão disponíveis. A consultoria pode ser online, presencial ou combinada, de acordo com sua necessidade."],["Como funciona a avaliação física?","A avaliação pode ser feita presencialmente ou por fotos, conforme o formato escolhido e as orientações do DU Personal."],["Recebo treino personalizado?","Sim. O treino é montado de acordo com seu objetivo, nível, rotina e estrutura disponível."],["Existe acompanhamento durante o processo?","Sim. A consultoria inclui suporte contínuo pelo WhatsApp e ajustes constantes para acompanhar sua evolução."],["Posso incluir dieta?","Existe a opção de consultoria com plano alimentar personalizado. Os detalhes são explicados na conversa inicial."],["Quais são os planos?","Há opções mensais, trimestrais e semestrais. O formato ideal depende do seu objetivo e do nível de acompanhamento desejado."]].map(([question,answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="final-cta"><div className="final-grid section reveal"><div><span className="eyebrow lime">DU PERSONAL</span><h2>Vamo querer<br />a sua <em>evolução.</em></h2></div><div><p>Conte onde você está e descubra qual é o próximo passo para treinar com mais clareza e propósito.</p><div className="final-actions"><ActionLink href={whatsappUrl}>Falar com o DU Personal</ActionLink><ActionLink href={instagramUrl} tone="ghost">Ver o Instagram</ActionLink></div></div></div></section>
    </main>
    <footer className="footer"><Brand /><p>Ensino com ciência. Treino com propósito.</p><a href={instagramUrl} target="_blank" rel="noopener noreferrer"><Camera size={18} /> @duh.personal</a><button type="button" onClick={() => setPrivacyOpen(true)}>Privacidade</button><span>© {new Date().getFullYear()} DU Personal</span></footer><a className="floating-whatsapp" href={whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label="Falar com o DU Personal"><MessageCircle /></a><dialog ref={dialog} className="privacy-dialog" onCancel={() => setPrivacyOpen(false)} onClose={() => setPrivacyOpen(false)}><button className="dialog-close" type="button" aria-label="Fechar política de privacidade" onClick={() => setPrivacyOpen(false)}><X /></button><span className="eyebrow">PRIVACIDADE</span><h2>Seus dados, sua escolha.</h2><p>Esta página não coleta dados por formulário. Os botões direcionam para Instagram, que possui política própria.</p><button className="button button-lime" type="button" onClick={() => setPrivacyOpen(false)}><Check /> Entendi</button></dialog>
  </div>;
}
export default App;


